### ISSUE TITLE
Documentation - Requirements

### ISSUE THREAD

**Issue by Ann-Onymous** [juliankay/FakeGPS#8]
You wrote this requires a BCDEDIT for Windows 8 and up (I am on Windows 10 64-bit) and got an error:
![image](https://cloud.githubusercontent.com/assets/18236224/14228886/dff72034-f8e9-11e5-94b1-f0b58853865f.png)

**Comment by juliankay** [comment]
Yes, that's correct. Unfortunately "Test Mode" doesn't work with Secure Boot.

It is mentioned on https://github.com/juliankay/FakeGPS#requirements but you may have missed it.

I deliberately did not suggest that people disable Secure Boot in order to use it, as obviously that recommendation would effect the security of people's machines. But you could disable Secure Boot if you wish to.
